### ISSUE TITLE
Enable x axis in shot noise plot to show analysis time (in addition to n_effective)

### ISSUE THREAD

**Issue by 123caj** [isoverse/isoorbi#24]
<img width="266" alt="image" src="https://github.com/isoverse/isoorbi/assets/5480056/349d9a20-9462-49b6-9de5-2823c165a813">

**Comment by 123caj** [comment]
Double x axis? Something along these lines?...

<img width="399" alt="image" src="https://github.com/isoverse/isoorbi/assets/5480056/525562ba-522d-4397-929c-910ab498098b">

**Comment by sebkopf** [comment]
implemented in v 1.2 with `x` argument allowing switch between ions and time. The double axis would be nice but not sure how to implement this while also allowing multiple isotopocules to be plotted in parallel (since the time to ions mapping is different for both). Okay to close this for now @123caj ?

**Comment by 123caj** [comment]
Super! Thanks so much
